# Generated by Django 5.2.4 on 2025-12-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, error_messages={'unique': 'Ya existe un producto con ese código.'}, max_length=50, unique=True),
        ),
    ]
