# Generated by Django 5.2.4 on 2025-11-05 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='OPEN', max_length=6)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_opened', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
