# Generated by Django 5.2.4 on 2025-11-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dte', to='sales.sale')),
            ],
        ),
    ]
