# Generated by Django 5.2.4 on 2025-11-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashdesk', '0001_initial'),
        ('sales', '0002_alter_saleitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='cashdesk.cashsession'),
        ),
    ]
